package caipsfa.db.hibernate;
// Generated 10-19-2016 11:40:37 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Doctores generated by hbm2java
 */
public class Doctores  implements java.io.Serializable {


     private int codigoDoctor;
     private String nombres;
     private String apellidos;
     private String especialidad;
     private String dui;
     private String nit;
     private String telefono;
     private String email;
     private String dependencia;
     private Set salidases = new HashSet(0);

    public Doctores() {
    }

	
    public Doctores(int codigoDoctor, String nombres, String apellidos, String especialidad, String dui, String nit, String telefono, String email, String dependencia) {
        this.codigoDoctor = codigoDoctor;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.especialidad = especialidad;
        this.dui = dui;
        this.nit = nit;
        this.telefono = telefono;
        this.email = email;
        this.dependencia = dependencia;
    }
    public Doctores(int codigoDoctor, String nombres, String apellidos, String especialidad, String dui, String nit, String telefono, String email, String dependencia, Set salidases) {
       this.codigoDoctor = codigoDoctor;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.especialidad = especialidad;
       this.dui = dui;
       this.nit = nit;
       this.telefono = telefono;
       this.email = email;
       this.dependencia = dependencia;
       this.salidases = salidases;
    }
   
    public int getCodigoDoctor() {
        return this.codigoDoctor;
    }
    
    public void setCodigoDoctor(int codigoDoctor) {
        this.codigoDoctor = codigoDoctor;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getEspecialidad() {
        return this.especialidad;
    }
    
    public void setEspecialidad(String especialidad) {
        this.especialidad = especialidad;
    }
    public String getDui() {
        return this.dui;
    }
    
    public void setDui(String dui) {
        this.dui = dui;
    }
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDependencia() {
        return this.dependencia;
    }
    
    public void setDependencia(String dependencia) {
        this.dependencia = dependencia;
    }
    public Set getSalidases() {
        return this.salidases;
    }
    
    public void setSalidases(Set salidases) {
        this.salidases = salidases;
    }




}


