package caipsfa.db.hibernate;
// Generated 10-19-2016 11:40:37 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Entradas generated by hbm2java
 */
public class Entradas  implements java.io.Serializable {


     private Integer idEntrada;
     private Productos productos;
     private Date fechaEntrada;
     private Integer cantidadIngreso;
     private Double precio;

    public Entradas() {
    }

    public Entradas(Productos productos, Date fechaEntrada, Integer cantidadIngreso, Double precio) {
       this.productos = productos;
       this.fechaEntrada = fechaEntrada;
       this.cantidadIngreso = cantidadIngreso;
       this.precio = precio;
    }
   
    public Integer getIdEntrada() {
        return this.idEntrada;
    }
    
    public void setIdEntrada(Integer idEntrada) {
        this.idEntrada = idEntrada;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public Date getFechaEntrada() {
        return this.fechaEntrada;
    }
    
    public void setFechaEntrada(Date fechaEntrada) {
        this.fechaEntrada = fechaEntrada;
    }
    public Integer getCantidadIngreso() {
        return this.cantidadIngreso;
    }
    
    public void setCantidadIngreso(Integer cantidadIngreso) {
        this.cantidadIngreso = cantidadIngreso;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }




}


