package caipsfa.db.hibernate;
// Generated 10-19-2016 11:40:37 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private int codigoProducto;
     private Proveedores proveedores;
     private Unidades unidades;
     private String nombre;
     private String descripcion;
     private int existencia;
     private Date fechaVencimiento;
     private Set salidases = new HashSet(0);
     private Set entradases = new HashSet(0);

    public Productos() {
    }

	
    public Productos(int codigoProducto, Proveedores proveedores, Unidades unidades, String nombre, String descripcion, int existencia, Date fechaVencimiento) {
        this.codigoProducto = codigoProducto;
        this.proveedores = proveedores;
        this.unidades = unidades;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.existencia = existencia;
        this.fechaVencimiento = fechaVencimiento;
    }
    public Productos(int codigoProducto, Proveedores proveedores, Unidades unidades, String nombre, String descripcion, int existencia, Date fechaVencimiento, Set salidases, Set entradases) {
       this.codigoProducto = codigoProducto;
       this.proveedores = proveedores;
       this.unidades = unidades;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.existencia = existencia;
       this.fechaVencimiento = fechaVencimiento;
       this.salidases = salidases;
       this.entradases = entradases;
    }
   
    public int getCodigoProducto() {
        return this.codigoProducto;
    }
    
    public void setCodigoProducto(int codigoProducto) {
        this.codigoProducto = codigoProducto;
    }
    public Proveedores getProveedores() {
        return this.proveedores;
    }
    
    public void setProveedores(Proveedores proveedores) {
        this.proveedores = proveedores;
    }
    public Unidades getUnidades() {
        return this.unidades;
    }
    
    public void setUnidades(Unidades unidades) {
        this.unidades = unidades;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getExistencia() {
        return this.existencia;
    }
    
    public void setExistencia(int existencia) {
        this.existencia = existencia;
    }
    public Date getFechaVencimiento() {
        return this.fechaVencimiento;
    }
    
    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }
    public Set getSalidases() {
        return this.salidases;
    }
    
    public void setSalidases(Set salidases) {
        this.salidases = salidases;
    }
    public Set getEntradases() {
        return this.entradases;
    }
    
    public void setEntradases(Set entradases) {
        this.entradases = entradases;
    }




}


