package caipsfa.db.hibernate;
// Generated 10-19-2016 11:40:37 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedores generated by hbm2java
 */
public class Proveedores  implements java.io.Serializable {


     private int codigoProveedor;
     private String nombreProveedor;
     private String direccion;
     private String contacto;
     private String numeroTelefono;
     private Set productoses = new HashSet(0);

    public Proveedores() {
    }

	
    public Proveedores(int codigoProveedor, String nombreProveedor, String direccion, String contacto, String numeroTelefono) {
        this.codigoProveedor = codigoProveedor;
        this.nombreProveedor = nombreProveedor;
        this.direccion = direccion;
        this.contacto = contacto;
        this.numeroTelefono = numeroTelefono;
    }
    public Proveedores(int codigoProveedor, String nombreProveedor, String direccion, String contacto, String numeroTelefono, Set productoses) {
       this.codigoProveedor = codigoProveedor;
       this.nombreProveedor = nombreProveedor;
       this.direccion = direccion;
       this.contacto = contacto;
       this.numeroTelefono = numeroTelefono;
       this.productoses = productoses;
    }
   
    public int getCodigoProveedor() {
        return this.codigoProveedor;
    }
    
    public void setCodigoProveedor(int codigoProveedor) {
        this.codigoProveedor = codigoProveedor;
    }
    public String getNombreProveedor() {
        return this.nombreProveedor;
    }
    
    public void setNombreProveedor(String nombreProveedor) {
        this.nombreProveedor = nombreProveedor;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }
    public String getNumeroTelefono() {
        return this.numeroTelefono;
    }
    
    public void setNumeroTelefono(String numeroTelefono) {
        this.numeroTelefono = numeroTelefono;
    }
    public Set getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set productoses) {
        this.productoses = productoses;
    }




}


