package caipsfa.db.hibernate;
// Generated 10-19-2016 11:40:37 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Unidades generated by hbm2java
 */
public class Unidades  implements java.io.Serializable {


     private Integer codigoUnidad;
     private String nombre;
     private String prefijo;
     private Set productoses = new HashSet(0);

    public Unidades() {
    }

	
    public Unidades(String nombre, String prefijo) {
        this.nombre = nombre;
        this.prefijo = prefijo;
    }
    public Unidades(String nombre, String prefijo, Set productoses) {
       this.nombre = nombre;
       this.prefijo = prefijo;
       this.productoses = productoses;
    }
   
    public Integer getCodigoUnidad() {
        return this.codigoUnidad;
    }
    
    public void setCodigoUnidad(Integer codigoUnidad) {
        this.codigoUnidad = codigoUnidad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPrefijo() {
        return this.prefijo;
    }
    
    public void setPrefijo(String prefijo) {
        this.prefijo = prefijo;
    }
    public Set getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set productoses) {
        this.productoses = productoses;
    }




}


